### ISSUE TITLE
(REQUEST) Feature/Function to extract KID from EU QR

### ISSUE THREAD

**Issue by azim92** [jeroentrappers/dart_cose#10]
Hi, may I request to add feature/function to extract the QR KID in the `protectedHeader` from `coseByte` in **_dart_cose_**?

```dart
final protectedHeader = items[_CBOR_DATA_PROTECTED_HEADER_INDEX];
```

```dart
var a = Cbor();
a.decodeFromList(coseByte);
List coseElement = a.getDecodedData().first;

final protectedHeader = coseElement[_CBOR_DATA_PROTECTED_HEADER_INDEX];

var b = Cbor();
b.decodeFromList(protectedHeader);
var kid = b.getDecodedData().first;
qrKid = base64Encode(kid[4]);
```

**Comment by jeroentrappers** [comment]
You mean https://github.com/jeroentrappers/dart_cose/blob/715c7abbd0db839f6027a640a9b05c280c9f6a8a/lib/src/util/header_util.dart#L20 ?

**Comment by azim92** [comment]
> You mean
> 
> https://github.com/jeroentrappers/dart_cose/blob/715c7abbd0db839f6027a640a9b05c280c9f6a8a/lib/src/util/header_util.dart#L20
> 
> ?

Ah I missed this. Ok will use this function instead. Thanks for pointing out!
