### ISSUE TITLE
Add COSE KID to `CoseResult`

### ISSUE THREAD

**Issue by jbx1** [jeroentrappers/dart_cose#12]
Knowing which KID was found in the COSE header is useful to identify which of the certificates was used, and thus the corresponding authority or additional information that the application could know about the KID (such as the country, which should match the country of the DGC, whether it was an NHS one or the eHealth one, whether it was revoked etc.). 

In cases when the KID was not found in the Map of kid-to-certificates, it is useful to know what the KID in the header was too. 

Refer to corresponding pull request which adds the `coseKid` to the `CoseResult`: https://github.com/jeroentrappers/dart_cose/pull/11

**Comment by jbx1** [comment]
@vanlooverenkoen any chance of publishing the latest version to pub.dev? The one there is quite old now.

**Comment by vanlooverenkoen** [comment]
Yes I will do that today.

**Comment by vanlooverenkoen** [comment]
I was thinking why we did not update to pub.dev.

We are still waiting on a pull request of asn1lib -> https://github.com/wstrange/asn1lib/pull/56 

We can only release a new version to pub.dev if that pull request is fixed. Right now you should be using a git import

**Comment by jbx1** [comment]
Ah ok, was wondering why it was left on an old version on pub.dev.
