### ISSUE TITLE
Support test certificates

### ISSUE THREAD

**Issue by Pelkmann-smartiot** [jeroentrappers/dart_cose#14]
Hi Jeroen,

are test certificates also supported? I have troubles with reading test certificates. With qr codes from vaccinated people it works like a charm, but I am not able to read qr codes from tested people.

I get the following error code when reading a qr code from a tested person

CoseErrorCode (CoseErrorCode.key_not_found)

Thanks!

Alex

**Comment by jeroentrappers** [comment]
Yes, all types of EUDCCs should work

**Comment by Pelkmann-smartiot** [comment]
Unfortunately, it does not work.

**Comment by Pelkmann-smartiot** [comment]
My bad - the issues is solved !!! Sry
